### ISSUE TITLE
Default Texture Tile Layer styling issue

### ISSUE THREAD

**Issue by Yonet** [microsoft/MapsSDK-Unity#39] opened 2020-01-07 02:29 UTC
**Describe the bug**
Following the wiki documentation for [Default Texture Tile Layer](https://github.com/microsoft/MapsSDK-Unity/wiki/Configuring-the-MapRenderer#defaulttexturetilelayer), changing the Imagery Type from Aerial to Symbolic doesn't change the texture of the map, as shown in the doc images. See image below.

**To Reproduce**
1. Go to docs and follow the DefaultTextureTile instructions to change the look: https://github.com/microsoft/MapsSDK-Unity/wiki/Configuring-the-MapRenderer#defaulttexturetilelayer
2. Change imagery type from aerial to symbolic.
3. See error on Unity scene window as shown in the image below.

**Expected behavior**
Texture Tile layer change to be reflected on the Unity Editor view and be similar to the Symbolic Light image in the docs.

**Screenshots**
![Screenshot (149)](https://user-images.githubusercontent.com/3523671/71863643-4fd6a380-30b2-11ea-980e-8105aeeb6024.png)

**Environment (please complete the following information):**
 - Unity version: 2018.4.14f1
 - Maps SDK NuGet Package version: 0.4.2

**Comment by kircher1** [comment] 2020-01-08 22:45
This is a dupe of #34.

**Closed by kircher1** 2020-01-08 22:45 UTC
Labels: bug
