### ISSUE TITLE
Editor crash

### ISSUE THREAD

**Issue by Pysiokot** [microsoft/MapsSDK-Unity#57] opened 2020-05-20 13:48 UTC
Sometimes in Unity Editor (mostly when hitting _Play_ button) editor just crashes. Sometimes even after code recompilation. 

Information that I can find in error.log file:

[...]
mono-2.0-bdwgc.dll caused an Access Violation (0xc0000005)
  in module mono-2.0-bdwgc.dll at 0033:3f446835.

Error occurred at 2020-05-20_152122.
C:\Program Files\Unity\Hub\Editor\2019.3.5f1\Editor\Unity.exe, run by UserName.

[...]

Mono DLL loaded successfully at 'C:\Program Files\Unity\Hub\Editor\2019.3.5f1\Editor\Data\MonoBleedingEdge\EmbedRuntime\mono-2.0-bdwgc.dll'.

Stack Trace of Crashed Thread 21044:
0x00007FF83F446835 (mono-2.0-bdwgc) mono_debugger_method_has_breakpoint
0x00007FF83F28BD04 (mono-2.0-bdwgc) mono_class_init
0x00007FF83F28CAFA (mono-2.0-bdwgc) mono_class_is_subclass_of
ERROR: SymGetSymFromAddr64, GetLastError: 'An attempt was made to access an invalid address.' (Address: 00007FF6B422027A)
0x00007FF6B422027A (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'An attempt was made to access an invalid address.' (Address: 00007FF6B3C93268)
0x00007FF6B3C93268 (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'An attempt was made to access an invalid address.' (Address: 00007FF6B3C8DF14)
0x00007FF6B3C8DF14 (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'An attempt was made to access an invalid address.' (Address: 00007FF6B3C8DB7D)
0x00007FF6B3C8DB7D (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'An attempt was made to access an invalid address.' (Address: 00007FF6B3C8D750)
0x00007FF6B3C8D750 (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'An attempt was made to access an invalid address.' (Address: 00007FF6B3C909DF)
0x00007FF6B3C909DF (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'An attempt was made to access an invalid address.' (Address: 00007FF6B42193DB)
0x00007FF6B42193DB (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'An attempt was made to access an invalid address.' (Address: 00007FF6B436B7D1)
0x00007FF6B436B7D1 (Unity) (function-name not available)
0x0000029133C73827 (UnityEngine.CoreModule) UnityEngine.Object.DestroyImmediate()
0x0000029133C736DB (UnityEngine.CoreModule) UnityEngine.Object.DestroyImmediate()
0x0000029135FAD263 (Microsoft.Maps.Unity) Microsoft.Maps.Unity.MapRenderer.#=zsL_wap6Qg25c()
0x0000029135FACBBB (Microsoft.Maps.Unity) Microsoft.Maps.Unity.MapRenderer.OnEnable()
0x000002915ED74968 (mscorlib) System.Object.runtime_invoke_void__this__()
0x00007FF83F37CBB0 (mono-2.0-bdwgc) mono_get_runtime_build_info
0x00007FF83F302122 (mono-2.0-bdwgc) mono_perfcounters_init
0x00007FF83F30B11F (mono-2.0-bdwgc) mono_runtime_invoke
ERROR: SymGetSymFromAddr64, GetLastError: 'An attempt was made to access an invalid address.'  (Address: 00007FF6B422186E)
0x00007FF6B422186E (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'An attempt was made to access an invalid address.' (Address: 00007FF6B421B5BD)
0x00007FF6B421B5BD (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'An attempt was made to access an invalid address.'  (Address: 00007FF6B41E51E5)
0x00007FF6B41E51E5 (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError:  'An attempt was made to access an invalid address.'  (Address: 00007FF6B41E3A9E)
0x00007FF6B41E3A9E (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError:  'An attempt was made to access an invalid address.' (Address: 00007FF6B42827E2)
0x00007FF6B42827E2 (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError:  'An attempt was made to access an invalid address.'  (Address: 00007FF6B41E6C86)
0x00007FF6B41E6C86 (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'An attempt was made to access an invalid address.'  (Address: 00007FF6B41ED1B7)
0x00007FF6B41ED1B7 (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'An attempt was made to access an invalid address.' (Address: 00007FF6B265B943)
0x00007FF6B265B943 (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError:  'An attempt was made to access an invalid address.' (Address: 00007FF6B2B4F829)
0x00007FF6B2B4F829 (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError:  'An attempt was made to access an invalid address.'  (Address: 00007FF6B2B5727B)
0x00007FF6B2B5727B (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'An attempt was made to access an invalid address.' (Address: 00007FF6B2B59F71)
0x00007FF6B2B59F71 (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'An attempt was made to access an invalid address.' (Address: 00007FF6B2B57B36)
0x00007FF6B2B57B36 (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError:  'An attempt was made to access an invalid address.' (Address: 00007FF6B2A85821)
0x00007FF6B2A85821 (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError:  'An attempt was made to access an invalid address.' (Address: 00007FF6B20AB991)
0x00007FF6B20AB991 (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError:  'An attempt was made to access an invalid address.' (Address: 00007FF6B2A01DC0)
0x00007FF6B2A01DC0 (Unity) (function-name not available)
0x00007FF8B6DC5C0D (USER32) CallWindowProcW
0x00007FF8B6DC57DC (USER32) DispatchMessageW
0x00007FF8B6DD1F73 (USER32) IsWindowVisible
0x00007FF8B803FDE4 (ntdll) KiUserCallbackDispatcher
0x00007FF8B5D61184 (win32u) NtUserMessageCall
0x00007FF8B6DC436A (USER32) GetWindowTextW
0x00007FF8B6DC3AFF (USER32) MapWindowPoints
0x00007FF8B2E8984E (uxtheme) IsCompositionActive
0x00007FF8B2EA2547 (uxtheme) Ordinal96
0x00007FF8B2E8C50F (uxtheme) IsCompositionActive
0x00007FF8B2E8BFF1 (uxtheme) IsCompositionActive
0x00007FF8B6DC403F (USER32) GetWindowTextW
ERROR: SymGetSymFromAddr64, GetLastError: 'An attempt was made to access an invalid address.' (Address: 00007FF6B2A020AC)
0x00007FF6B2A020AC (Unity) (function-name not available)
0x00007FF8B6DC5C0D (USER32) CallWindowProcW
0x00007FF8B6DC5602 (USER32) DispatchMessageW
ERROR: SymGetSymFromAddr64, GetLastError: 'An attempt was made to access an invalid address.' (Address: 00007FF6B2A0B0E6)
0x00007FF6B2A0B0E6 (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError:  'An attempt was made to access an invalid address.' (Address: 00007FF6B2A14CFA)
0x00007FF6B2A14CFA (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'An attempt was made to access an invalid address.' (Address: 00007FF6B599E542)
0x00007FF6B599E542 (Unity) (function-name not available)
0x00007FF8B7EB7BD4 (KERNEL32) BaseThreadInitThunk
0x00007FF8B800CE51 (ntdll) RtlUserThreadStart

[...]

Info from Editor.log file:

[...]
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) UnityEngine.Object.DestroyImmediate (UnityEngine.Object,bool) [0x00008] in <58a34b0a618d424bb5fc18bb9bcdac20>:0
  at UnityEngine.Object.DestroyImmediate (UnityEngine.Object) [0x00005] in <58a34b0a618d424bb5fc18bb9bcdac20>:0
  at Microsoft.Maps.Unity.MapRenderer.#=zsL_wap6Qg25c () [0x0006f] in <42cb96a8f69545b4a3c281ad0b41eb7a>:0
  at Microsoft.Maps.Unity.MapRenderer.OnEnable () [0x00001] in <42cb96a8f69545b4a3c281ad0b41eb7a>:0
  at (wrapper runtime-invoke) object.runtime_invoke_void__this__ (object,intptr,intptr,intptr) [0x00020] in <437ba245d8404784b9fbab9b439ac908>:0

=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
[...]

**Comment by luk77** [comment] 2020-05-20 14:33
I have the same problem. It occurs randomly but quite often, usually after running the application in the editor and clicking "stop".

Here are some crash dumps:
[Crash_2020-05-20_142309299.zip](https://github.com/microsoft/MapsSDK-Unity/files/4657462/Crash_2020-05-20_142309299.zip)
[Crash_2020-05-20_142421864.zip](https://github.com/microsoft/MapsSDK-Unity/files/4657463/Crash_2020-05-20_142421864.zip)
[Crash_2020-05-20_142629559.zip](https://github.com/microsoft/MapsSDK-Unity/files/4657466/Crash_2020-05-20_142629559.zip)

It would be great if someone could provide information on how to avoid this problem.
Thanks.

**Comment by kircher1** [comment] 2020-05-20 16:12
Sounds like this bug we filed to Unity: https://issuetracker.unity3d.com/issues/editor-crash-when-entering-and-exiting-playmode-for-a-few-times-with-microsoft-maps-sdk

**Comment by kircher1** [comment] 2020-06-12 05:10
2019.4 now has a fix for crash. Closing.

**Closed by kircher1** 2020-06-12 05:10 UTC
Labels: bug, external

**Comment by Neutrinora** [comment] 2020-06-27 09:07
I think need to reopen this issue.

I'm using Unity 2019.4.0f1

Reproduce steps are the same with: https://issuetracker.unity3d.com/issues/editor-crash-when-entering-and-exiting-playmode-for-a-few-times-with-microsoft-maps-sdk

Additional information:
Same result on 2 different Windows 10 computers,
Results "**frequent**" editor crashes **ONLY** if following conditions are fit **when clicking "Exit Play Mode"** :

**Cond 1** - While has an active tile download progress (Tested by using Play/Pause button as fast as possible).
**Cond 2** - While MapScene transitioning (probably caused by **Cond 1**)

**Comment by Neutrinora** [comment] 2020-06-27 09:14
Oh, i've just seen that it is not 2019.4.0f1.
I'm going to update my editor to try in 2019.4.1f1

> RESOLUTION NOTE (FIX VERSION 2019.4):
> Fixed in: 2019.4.1f1
