### ISSUE TITLE
MapPin doesn't move when changing LatLonAlt in runtime

### ISSUE THREAD

**Issue by Pysiokot** [microsoft/MapsSDK-Unity#66] opened 2020-06-16 10:59 UTC
In my scenario I spawn f.ex. 10 pins at the start and then I'm changing LatLonAlts of these pins to make them move above map and with it. In previous versions of your package this MapPins were moving properly but in version 0.9.0 changing LatLonAlt of MapPin doesn't move it anymore.

Is this bug or expected behaviour?

**Comment by kircher1** [comment] 2020-06-16 18:04
This looks like a regression. I've narrowed it down to a couple of issues in the [MapPin](https://github.com/microsoft/MapsSDK-Unity/blob/master/SupportingScripts/Runtime/Scripts/MapRenderer/MapPin/MapPin.cs) script. I'll try to share a fix shortly.

**Comment by kircher1** [comment] 2020-06-16 18:57
Here's the updates I made to the MapPin script which fix this issue: https://github.com/microsoft/MapsSDK-Unity/pull/67

We'll release this in the next version of the SDK, but in the meantime, you can copy this file over the MapPin.cs in the Unity package to get it working now.

**Comment by HKBSC** [comment] 2020-06-16 21:54
Replacing contents of MapPin.cs file with the new code fixes the issue at first but the problem somehow reoccurs after restarting unity or building to device.

**Comment by kircher1** [comment] 2020-06-16 22:00
Can you tell if the MapPin.cs file is getting reverted back to the older version? I'm wondering if Unity is somehow refreshing the package contents when starting the editor/building.

**Comment by HKBSC** [comment] 2020-06-16 22:04
Yes, that's what's happening. In which case, will you be able to push an update to the package manager version?

**Comment by HKBSC** [comment] 2020-06-16 22:07
And weirdly if the script is still open on Visual Studio, it still shows the newer version. But I can see the reverted code on the Unity preview when I click on it in the project.

**Comment by kircher1** [comment] 2020-06-16 22:10
Ok thanks for confirming at least. That's too bad :( 

Maybe there is some way to get Unity not to override it... We'll have to investigate that to see what's possible.

A workaround, which is more involved, would be to copy the cached npm files for microsoft.maps.unity to a local directory, and point Unity's package manager to that directory (via the '+' button). Then the package manager won't be syncing it with the NPM registry and the script shouldn't change.

Anyways, given the various regressions in the MapPin functionality, we'll look at getting an update out this week. Will keep you posted on this thread.

**Comment by kircher1** [comment] 2020-06-18 19:24
Fix is in 0.9.1.

**Closed by kircher1** 2020-06-18 19:24 UTC
Labels: bug
