### ISSUE TITLE
Non-MR Project Potential Issue

### ISSUE THREAD

**Issue by jasonnewbatt** [microsoft/MapsSDK-Unity#82] opened 2020-08-07 15:26 UTC
Is this project supported for non Mixed Reality usage? I do not have a Mixed Reality Head Mounted Device. But I'm getting errors in the editor for Unity 2020.1.0f1.

I have just created a new Unity Project, included the MapsSDK, and I'm getting a rendering error "ArgumentException: Failed SupportsTextureFormat; format is not a valid TextureFormat" which ultimately results in the Unity crashing citing a GC issue. The errors occurs when trying to render the Map in the editor ("Show Map Data in Editor" tickbox is selected). The map doesn't render fully when the project is built either at this point, with only the TextMesh Pro copyright being visible.

I suspect this is related to the Shaders. I'm not a professional developer for Unity, more a hobby developer, so please excuse any incorrect terminology usage here.

I get the same error when upgrading the sample project to 2020.1.0f1 too.

Here is the Full stack error: [Full Error.txt](https://github.com/microsoft/MapsSDK-Unity/files/5042185/Full.Error.txt)

I also include a screenshot of the editor window.
![Unity Editor Screenshot](https://user-images.githubusercontent.com/13446392/89660868-db731580-d8c9-11ea-9cf4-09244ae0908f.png)

Didn't want to raise as an issue in case this is solved by having an MR device.

Any help would be appreciated.

**Comment by kircher1** [comment] 2020-08-07 17:19
This could also be an issue with the platform. Is this on Windows? In general though, no headset is required for the SDK to work and could be used in a desktop app.

Also are you using URP or HDRP? The SDK currently doesn't support scriptable render pipelines.

**Comment by jasonnewbatt** [comment] 2020-08-07 18:14
Yes, this is on Windows (latest build). I got the same issue for both upgrading the existing sample project to 2020.1 and also in my own project which is SRP. Appreciate SRP is not supported, but as the existing project didnt work for me im guessing this may be platform related.

**Comment by kircher1** [comment] 2020-08-07 18:44
If this project is using SRP, the pink material is expected because the shaders that the SDK uses would be invalid.

However, the error log text that you provided has something to do with missing texture format support. I don't believe that is related to SRP at all, and moreover, the texture formats the SDK uses should definitely be supported on Windows machines. So, that's a bit surprising.

Have you tried Unity 2019.4 and seen any issues there? We've not tested Unity 2020.1, so it's possible the texture format support issue is something specific to the newer Unity versions.

**Comment by jasonnewbatt** [comment] 2020-08-07 19:02
Exactly, the screenshot attached was from my project using the SRP. I will give this a try on 2019.4 to see if this is an issue with my local environment somewhere, if it works then we will know its platform and 2020.1 related. I will give it a test and revert back soon! Thanks for the support!

**Comment by jasonnewbatt** [comment] 2020-08-08 14:34
So this works perfectly in Unity 2019.4.7f1 (latest LTS version). However when upgrading to Unity 2020 it fails. Platform Issue.

Would be great to see this adopt the URP / HDRP at some point. I expect there may be some deprecated features in the built in shader moving to URP. But that's a guess on my part.

**Comment by kircher1** [comment] 2020-08-08 18:25
Thanks for checking, and I've also confirmed this is an issue with 2020.1. One of the Unity APIs used internally within the SDK to check which texture formats are supported on the device is now throwing an argument exception in 2020.1 (not in 2019.4). This exception causes the error log spew and the map fails to initialize. I'll look at what needs to be done to mitigate this in lieu of Unity fixing it.

**Comment by kircher1** [comment] 2020-08-13 00:24
The 2020.1 issue has been fixed in the latest version of the SDK (0.9.2). 

For URP support, there was actually an issue filed for that awhile back when it was called LWRP.  #15

**Closed by kircher1** 2020-08-13 00:24 UTC
Labels: question
