### ISSUE TITLE
MapLocationFinder.FindLocationsAt Not working (Inverse location)

### ISSUE THREAD

**Issue by Nalistic36** [microsoft/MapsSDK-Unity#122] opened 2021-06-24 15:19 UTC
**Describe the bug**
MapLocationFinder.FindLocationsAt doesnt return any valid information.

**To Reproduce**
1. Open any example Scene.
2. Create a new MonoBehaviour script and add this method

`

        public async void GetStreetName(Microsoft.Geospatial.LatLon position)
        {
        if (MapSession.Current == null || string.IsNullOrWhiteSpace(MapSession.Current.DeveloperKey))
        {
            return;
        }

        MapLocationOptions mapOptions = new MapLocationOptions();
        var result = await MapLocationFinder.FindLocationsAt(position,mapOptions);
        
        if (result.Locations.Count > 0 && result.Status == MapLocationFinderStatus.Success)
        {
            Debug.Log("Display Name: " + result.Locations[0].DisplayName);
            Debug.Log("Landmark:" + result.Locations[0].Address.Landmark);
            Debug.Log("Formatted Address: " + result.Locations[0].Address.FormattedAddress);
            Debug.Log("AddressLine: " + result.Locations[0].Address.AddressLine);
            Debug.Log("AdminDistrict: " + result.Locations[0].Address.AdminDistrict);
            Debug.Log("Neighborhood: " + result.Locations[0].Address.Neighborhood);
            Debug.Log("PostalCode: " + result.Locations[0].Address.PostalCode);
            Debug.Log("Locality: " + result.Locations[0].Address.Locality);
        }
    }

`

**Expected behavior**
The expected behavior was a detail information about the location.

**Screenshots**
![Captura](https://user-images.githubusercontent.com/71155386/123288036-7e974280-d50f-11eb-8a9d-5ad38cb73ca9.PNG)

**Environment (please complete the following information):**
 - Unity version: [e.g. 2019.4.27f1]
 - Maps SDK Package version: [e.g. 0.11.0]

**Comment by kircher1** [comment] 2021-06-24 18:45
Are there any results (e.g. an address line), when using the REST service directly?

    https://dev.virtualearth.net/REST/v1/Locations/{lat},{lon}?maxRes=5&key={key}

Fill in the {variables} and then you can view the json result in your browser. In general, the values should match what the Unity API returns.

**Comment by Nalistic36** [comment] 2021-06-25 07:29
Hello,

Yes, the REST service is fully working. 

Is it posible to use the Service directly as a workarround to the FindLocationsAt? the copyright label returned looks restrictive. (Copyright © 2021 Microsoft and its suppliers. All rights reserved. This API cannot be accessed and the content and any results may not be used, reproduced or transmitted in any manner without express written permission from Microsoft Corporation)

**Comment by kircher1** [comment] 2021-06-25 08:07
The APIs in Unity are wrappers over this REST service (see docs [here](https://docs.microsoft.com/en-us/bingmaps/rest-services/locations/find-a-location-by-point)). The URL I shared is slightly simplified. There are some extra parameters the SDK adds which could be the cause of different/empty results. The full URL used by the SDK can be recovered by uncommenting the Debug.Log [here](https://github.com/microsoft/MapsSDK-Unity/blob/master/SupportingScripts/Runtime/Scripts/MapServices/Endpoints.cs).

**Comment by Nalistic36** [comment] 2021-06-25 09:55
Hello,

I have done my own wrapper method and at the first attempt I had the same issues that when using FindLocationAt, I doubt the issue is similar, but just in case, my issue with my wrapper was using ToString default overload, and changed the float location from "0.00" to "0,00".

As a workarround, if anyone faces this same issue, my wrapper is:

`

    using System.Collections;
    using UnityEngine;

    namespace Microsoft.Maps.Unity.Search
    {
        public static class CustomMapLocationFinder
        {
            public static IEnumerator FindLocationsAt(Microsoft.Geospatial.LatLon location, System.Action<Address> OnSuccess)
            {
                string latitud = location.LatitudeInDegrees.ToString(System.Globalization.CultureInfo.InvariantCulture);
                string longitude = location.LongitudeInDegrees.ToString(System.Globalization.CultureInfo.InvariantCulture);

                string url = string.Concat("https://dev.virtualearth.net/REST/v1/Locations/", latitud, ",", longitude, "?maxRes=5&key=", MapSession.Current.DeveloperKey);

                using (UnityEngine.Networking.UnityWebRequest request = UnityEngine.Networking.UnityWebRequest.Get(url))
                {
                    yield return request.SendWebRequest();

                    if (!request.isHttpError && !request.isNetworkError)
                    {
                        Debug.Log(request.downloadHandler.text);
                        MicrosoftResult result = JsonUtility.FromJson<MicrosoftResult>(request.downloadHandler.text);

                        if (result.statusCode == 200 && result.resourceSets.Length > 0 && result.resourceSets[0].resources.Length > 0)
                        {
                            OnSuccess(result.resourceSets[0].resources[0].address);
                        }
                    }
                }
            }
        }

        [System.Serializable]
        public class MicrosoftResult
        {
            public string authenticationResultCode;
            public string brandLogoUri;
            public string copyright;
            public ResourceSets[] resourceSets;
            public int statusCode;
            public string statusDescription;
            public string traceId;
        }

        [System.Serializable]
        public class ResourceSets
        {
            public int estimatedTotal;
            public Resources[] resources;
        }

        [System.Serializable]
        public class Resources
        {
            public int estimatedTotal;
            public float[] bbox;
            public Address address;
            public Point point;
            public string confidence;
            public string entityType;
            public string[] matchCodes;
        }

        [System.Serializable]
        public class Point
        {
            public string type;
            public float[] coordinates;
        }

        [System.Serializable]
        public class GeocodePoints
        {
            public string type;
            public float[] coordinates;
            public string calculationMethod;
            public string[] usageTypes;
        }

        [System.Serializable]
        public class Address
        {
            public string addressLine;
            public string adminDistrict;
            public string adminDistrict2;
            public string countryRegion;
            public string formattedAddress;
            public string locality;
            public string postalCode;
        }

        [System.Serializable]
        public class Intersection
        {
            public string baseStreet;
            public string secondaryStreet1;
            public string secondaryStreet2;
            public string intersectionType;
            public string displayName;
        }
    }

`

and use it like this:


    public void GetStreetName(Microsoft.Geospatial.LatLon position)
    {
        if (MapSession.Current == null || string.IsNullOrWhiteSpace(MapSession.Current.DeveloperKey))
        {
            return;
        }

        StartCoroutine(CustomMapLocationFinder.FindLocationsAt(position, LocationSelected));
    }

    public void LocationSelected(Address address)
    {
        Debug.Log("Formatted Address: " + address.formattedAddress);
        Debug.Log("AddressLine: " + address.addressLine);
        Debug.Log("AdminDistrict: " + address.adminDistrict);
        Debug.Log("PostalCode: " + address.postalCode);
        Debug.Log("Locality: " + address.locality);
    }

**Comment by kircher1** [comment] 2021-06-25 16:47
@Nalistic36 thanks for the update.

I would still like to understand the cause of the existing API not working. Would you be able to share an example URL that the existing API produces by enabling that Debug.Log I mentioned in my previous comment? **Just be sure to remove your developer key from the URL before sharing!**

The point about string formatting is interesting. It would be good to rule out whether or not that is the issue.

**Comment by Nalistic36** [comment] 2021-06-28 07:20
Hello,

I have enable the log and it looks the issue is the same I had first, this is the url it returned

https://dev.virtualearth.net/REST/v1/Locations/40,418142645539,-3,69995652965643?maxRes=5&c=es-ES&ur=ES&sftr=teolin&key=*****************************************************

(I am using the project from Spain)

**Comment by kircher1** [comment] 2021-06-28 17:48
Yep, thanks for confirming! This should be a straight forward fix. The string interpolation used throughout the wrapper code needs to be updated to use the invariant culture for formatting.

**Comment by kircher1** [comment] 2021-09-17 20:29
Fixed in 0.11.1

**Closed by kircher1** 2021-09-17 20:29 UTC
Labels: bug
